[install]
is_configured = false
build = 1

[launcher]
author = MB2 Analytics
description = CIM Data Generator - select Splunk CIM data models and generate dynamic sample data to test those data models.
version = 1.0.0

[ui]
is_visible = 1
label = CIM Data Generator

[package]
id = cimdg
check_for_updates = false
