[role_cimdg_admin]
importRoles = user
srchIndexesAllowed = synthetic_cim;_internal
srchIndexesDefault = synthetic_cim

[role_cimdg_user]
importRoles = user
srchIndexesAllowed = synthetic_cim
srchIndexesDefault = synthetic_cim
