[synthetic_authentication]
search = sourcetype="cimdg:synthetic:authentication"

[synthetic_network_traffic]
search = sourcetype="cimdg:synthetic:network_traffic"

[synthetic_web]
search = sourcetype="cimdg:synthetic:web"

[synthetic_endpoint_processes]
search = sourcetype="cimdg:synthetic:endpoint_processes"

[synthetic_malware]
search = sourcetype="cimdg:synthetic:malware"

[synthetic_intrusion_detection]
search = sourcetype="cimdg:synthetic:intrusion_detection"

[synthetic_dns]
search = sourcetype="cimdg:synthetic:dns"

[synthetic_endpoint_filesystem]
search = sourcetype="cimdg:synthetic:endpoint_filesystem"

[synthetic_endpoint_registry]
search = sourcetype="cimdg:synthetic:endpoint_registry"

[synthetic_endpoint_services]
search = sourcetype="cimdg:synthetic:endpoint_services"

[synthetic_endpoint_ports]
search = sourcetype="cimdg:synthetic:endpoint_ports"

[synthetic_vulnerabilities]
search = sourcetype="cimdg:synthetic:vulnerabilities"

[synthetic_change]
search = sourcetype="cimdg:synthetic:change"

[synthetic_email]
search = sourcetype="cimdg:synthetic:email"

[synthetic_network_sessions]
search = sourcetype="cimdg:synthetic:network_sessions"

[synthetic_alerts]
search = sourcetype="cimdg:synthetic:alerts"

[synthetic_dlp]
search = sourcetype="cimdg:synthetic:dlp"

[synthetic_certificates]
search = sourcetype="cimdg:synthetic:certificates"

[synthetic_updates]
search = sourcetype="cimdg:synthetic:updates"

[synthetic_databases]
search = sourcetype="cimdg:synthetic:databases"

[synthetic_performance]
search = sourcetype="cimdg:synthetic:performance"

[synthetic_jvm]
search = sourcetype="cimdg:synthetic:jvm"

[synthetic_inventory]
search = sourcetype="cimdg:synthetic:inventory"

[synthetic_ticket_management]
search = sourcetype="cimdg:synthetic:ticket_management"

[synthetic_interprocess_messaging]
search = sourcetype="cimdg:synthetic:interprocess_messaging"

[synthetic_event_signatures]
search = sourcetype="cimdg:synthetic:event_signatures"

[synthetic_splunk_audit]
search = sourcetype="cimdg:synthetic:splunk_audit"

[synthetic_data_access]
search = sourcetype="cimdg:synthetic:data_access"
