[synthetic_authentication]
search = sourcetype="synthetic:authentication"

[synthetic_network_traffic]
search = sourcetype="synthetic:network_traffic"

[synthetic_web]
search = sourcetype="synthetic:web"

[synthetic_endpoint_processes]
search = sourcetype="synthetic:endpoint_processes"

[synthetic_malware]
search = sourcetype="synthetic:malware"

[synthetic_intrusion_detection]
search = sourcetype="synthetic:intrusion_detection"

[synthetic_dns]
search = sourcetype="synthetic:dns"
