[cim_synthetic_data://authentication]
model = authentication
events_per_interval = 10
index = synthetic_cim
interval = 60
disabled = 1
python.version = python3

[cim_synthetic_data://network_traffic]
model = network_traffic
events_per_interval = 10
index = synthetic_cim
interval = 60
disabled = 1
python.version = python3

[cim_synthetic_data://web]
model = web
events_per_interval = 10
index = synthetic_cim
interval = 60
disabled = 1
python.version = python3

[cim_synthetic_data://endpoint_processes]
model = endpoint
events_per_interval = 10
index = synthetic_cim
interval = 60
disabled = 1
python.version = python3

[cim_synthetic_data://malware]
model = malware
events_per_interval = 10
index = synthetic_cim
interval = 60
disabled = 1
python.version = python3

[cim_synthetic_data://intrusion_detection]
model = intrusion_detection
events_per_interval = 10
index = synthetic_cim
interval = 60
disabled = 1
python.version = python3

[cim_synthetic_data://dns]
model = dns
events_per_interval = 10
index = synthetic_cim
interval = 60
disabled = 1
python.version = python3
