[synthetic:authentication]
KV_MODE = json
TIME_FORMAT = %s.%6N
TIME_PREFIX = "_time":\s*
MAX_TIMESTAMP_LOOKAHEAD = 20
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
category = Splunk App Add-on Builder

[synthetic:network_traffic]
KV_MODE = json
TIME_FORMAT = %s.%6N
TIME_PREFIX = "_time":\s*
MAX_TIMESTAMP_LOOKAHEAD = 20
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
category = Splunk App Add-on Builder

[synthetic:web]
KV_MODE = json
TIME_FORMAT = %s.%6N
TIME_PREFIX = "_time":\s*
MAX_TIMESTAMP_LOOKAHEAD = 20
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
category = Splunk App Add-on Builder

[synthetic:endpoint_processes]
KV_MODE = json
TIME_FORMAT = %s.%6N
TIME_PREFIX = "_time":\s*
MAX_TIMESTAMP_LOOKAHEAD = 20
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
category = Splunk App Add-on Builder

[synthetic:malware]
KV_MODE = json
TIME_FORMAT = %s.%6N
TIME_PREFIX = "_time":\s*
MAX_TIMESTAMP_LOOKAHEAD = 20
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
category = Splunk App Add-on Builder

[synthetic:intrusion_detection]
KV_MODE = json
TIME_FORMAT = %s.%6N
TIME_PREFIX = "_time":\s*
MAX_TIMESTAMP_LOOKAHEAD = 20
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
category = Splunk App Add-on Builder

[synthetic:dns]
KV_MODE = json
TIME_FORMAT = %s.%6N
TIME_PREFIX = "_time":\s*
MAX_TIMESTAMP_LOOKAHEAD = 20
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
category = Splunk App Add-on Builder
