[script:cimdg_generate]
match                 = /cimdg/generate
script                = cim_generate_handler.py
scripttype            = persist
handler               = cim_generate_handler.GenerateHandler
requireAuthentication = true
output_mode           = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true
python.version        = python3

[script:cimdg_status]
match                 = /cimdg/status
script                = cim_status_handler.py
scripttype            = persist
handler               = cim_status_handler.StatusHandler
requireAuthentication = true
output_mode           = json
passPayload           = true
passHttpHeaders       = true
passHttpCookies       = true
python.version        = python3
