[eventtype=synthetic_authentication]
authentication = enabled

[eventtype=synthetic_network_traffic]
network = enabled
communicate = enabled

[eventtype=synthetic_web]
web = enabled

[eventtype=synthetic_endpoint_processes]
process = enabled
report = enabled

[eventtype=synthetic_malware]
malware = enabled
attack = enabled

[eventtype=synthetic_intrusion_detection]
ids = enabled
attack = enabled

[eventtype=synthetic_dns]
network = enabled
resolution = enabled
dns = enabled

[eventtype=synthetic_endpoint_filesystem]
endpoint = enabled
filesystem = enabled

[eventtype=synthetic_endpoint_registry]
endpoint = enabled
registry = enabled

[eventtype=synthetic_endpoint_services]
endpoint = enabled
service = enabled

[eventtype=synthetic_endpoint_ports]
endpoint = enabled
port = enabled
listening = enabled

[eventtype=synthetic_vulnerabilities]
report = enabled
vulnerability = enabled

[eventtype=synthetic_change]
change = enabled

[eventtype=synthetic_email]
email = enabled

[eventtype=synthetic_network_sessions]
network = enabled
session = enabled

[eventtype=synthetic_alerts]
alert = enabled

[eventtype=synthetic_dlp]
dlp = enabled
incident = enabled

[eventtype=synthetic_certificates]
certificate = enabled

[eventtype=synthetic_updates]
update = enabled
status = enabled

[eventtype=synthetic_databases]
database = enabled

[eventtype=synthetic_performance]
performance = enabled
os = enabled

[eventtype=synthetic_jvm]
jvm = enabled

[eventtype=synthetic_inventory]
inventory = enabled

[eventtype=synthetic_ticket_management]
ticketing = enabled

[eventtype=synthetic_interprocess_messaging]
messaging = enabled

[eventtype=synthetic_event_signatures]
track_event = enabled
signature = enabled

[eventtype=synthetic_splunk_audit]
audit = enabled

[eventtype=synthetic_data_access]
data = enabled
access = enabled
