[eventtype=synthetic_authentication]
authentication = enabled

[eventtype=synthetic_network_traffic]
network = enabled
communicate = enabled

[eventtype=synthetic_web]
web = enabled

[eventtype=synthetic_endpoint_processes]
process = enabled
report = enabled

[eventtype=synthetic_malware]
malware = enabled
attack = enabled

[eventtype=synthetic_intrusion_detection]
ids = enabled
attack = enabled

[eventtype=synthetic_dns]
network = enabled
resolution = enabled
dns = enabled
